Flash_Forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("sign-in/", views.SignInView.as_view(), name="sign-in"),
    path("sign-up/", views.SignUpView.as_view(), name="sign-up"),
    path("sign-out/", views.sign_out, name="sign-out"),
    path("complete-profile/", views.CompleteProfileView.as_view(), name="complete-profile"),
    path("", views.HomePageView.as_view(), name="homepage")
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone

def profile_photo_upload_to(instance, filename):
    return "profile_photos/user_{0}/{1}".format(instance.id, filename)

# Create your models here.
class User(AbstractUser):
    profile_photo = models.ImageField(upload_to=profile_photo_upload_to, default="profile_photos/default.png")


class Tag(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title


class Thread(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # User who posted this topic
    tags = models.ManyToManyField("Tag") # Tags associated with a question/topic
    description = models.TextField(blank=True) # Description given to this topic
    created_at = models.DateTimeField(default=timezone.now)
    attachments = models.ManyToManyField("FileAttachment", blank=True) # File attachments

    def __str__(self):
        return self.title


class Post(models.Model):
    thread = models.ForeignKey("Thread", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    attachments = models.ManyToManyField("FileAttachment", blank=True)
    content = models.TextField()
    parent = models.ManyToManyField("self", blank=True, related_name="responses")
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class FileAttachment(models.Model):
    file = models.FileField(upload_to="attachments/")

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2"
        )

core/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from django.contrib import messages

# Create your views here.
def sign_out(request):
    logout(request)
    return redirect(reverse("core:sign-in"))

class SignInView(View):
    template_name = "core/sign-in.html"
    context = {
        "title": "Sign In | Flash Forum"
    }

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, password=password, username=username)
        if user is not None:
            login(request, user)
            return redirect(reverse("core:homepage"))
        messages.add_message(request, messages.ERROR, "Incorrect credentials!")
        return redirect(reverse("core:sign-in"))


class SignUpView(View):
    template_name = "core/sign-up.html"
    context = {
        "title": "Sign Up | Flash Forum"
    }

    def get(self, request, *args, **kwargs):
        form = SignUpForm()
        self.context["form"] = form
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("core:complete-profile")
        self.context["form"] = form
        return render(request, self.template_name, self.context)


class CompleteProfileView(LoginRequiredMixin, View):
    template_name = "core/complete-profile.html"
    login_url = reverse_lazy("core:sign-in")
    context = {
        "title": "Complete Profile | Flash Forum"
    }

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)


class HomePageView(LoginRequiredMixin, View):
    template_name = "core/homepage.html"
    login_url = reverse_lazy("core:sign-in")
    context = {
        "title": "Home | Flash Forum"
    }

    def get(self, request, *args, **kwargs):  
        return render(request, self.template_name, self.context)

core/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    <title>{{ title }}</title>
    {% block css %}
    {% endblock %}
</head>

<body>
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    {% load static %}
    <script src="{% static 'core/js/main.js' %}"></script>
</body>

</html>

core/templates/core/complete-profile.html
{% extends '_base.html' %}

{% block content %}
<main>
    {% include 'partials/navbar_auth.html' %}
    <div class="container">
        <h2><b>UPLOAD YOUR PHOTO</b></h2>
        <div class="row">
            <div class="col-md-2">
                <form action="" method="post">
                    <div class="my-3">
                        <input type="file" class="d-none" name="profile_photo" id="profile_photo">
                        <label for="profile_photo">
                            <img style="width: 100%; height: 200px; object-fit:contain;" src="{{ request.user.profile_photo.url }}"
                                alt="profile_photo">
                        </label>
                    </div>
                    <button class="btn btn-primary w-100">Continue</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

core/templates/core/homepage.html
{% extends "_base.html" %}

{% block content %}
<h1>Home Page View</h1>
{% endblock %}

core/templates/core/sign-in.html
{% extends "_base.html" %}

{% block css %}
{% load static %}
<style>
    main {
        background: url("{% static 'core/images/background-img.jpg' %}") rgba(0, 0, 100, 0.6);
        background-repeat: no-repeat;
        background-size: cover;
        background-blend-mode: multiply;
    }

    .overlay {
        position: absolute;
        top: 0;
        bottom: 0;
        right: 0;
        left: 0;
        background-color: rgba(0, 0, 100, 0.4);
    }
</style>
{% endblock %}

{% block content %}
<main>
    {% include 'partials/navbar_unauth.html' %}
    <div class="container">
        
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-8">
                <div id="text-container">
                    <h1>
                        Discuss problems <br>with industry experts.<br>Find answers.
                    </h1>
                    <p>
                        Have a question on your mind?<br>
                        Start a conversation with our community.
                    <p>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-4">
                <form id="auth-form" action="{% url 'core:sign-in' %}" method="post">
                    <div class="p-3" id="heading-container">
                        <h3 class="text-center">Sign In</h3>
                    </div>
                    {% csrf_token %}
                    <div class="d-flex flex-column p-4">
                        <div class="mb-4">
                            <input name="username" type="text" placeholder="Email or Username" required class="form-control" id="email-username"/>
                        </div>
                        <div class="mb-4">
                            <input name="password" type="password" placeholder="Password" required class="form-control" id="password"/>
                        </div>
                        <div class="mb-4">
                            <button class="btn btn-primary rounded-pill w-100">Sign In</button>
                        </div>
                        <div>
                            <p class="form-text">Do not have an account? <a href="{% url 'core:sign-up' %}" class="link-primary">Click Here</a></p>
                        </div>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }} form-text"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
        
    </div>
</main>

{% endblock %}

<!-- Image Credit: Photo by fauxels from Pexels -->

core/templates/core/sign-up.html
{% extends "_base.html" %}

{% block css %}
{% load static %}
<style>
    main {
        background: url("{% static 'core/images/background-img.jpg' %}") rgba(0, 0, 100, 0.6);
        background-repeat: no-repeat;
        background-size: cover;
        background-blend-mode: multiply;
    }
</style>
{% endblock %}

{% block content %}
<main>
    {% include 'partials/navbar_unauth.html' %}

    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-8">
                <div id="text-container">
                    <h1>
                        Join our community<br> of experts.<br>Grow with us.
                    </h1>
                    <p>
                        Have a question on your mind?<br>
                        Join our community and expand your knowledge.
                    <p>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-4">
                <form id="auth-form" action="{% url 'core:sign-up' %}" method="post">
                    <div class="p-3" id="heading-container">
                        <h3 class="text-center">Sign Up</h3>
                    </div>
                    {% csrf_token %}
                    <div class="d-flex flex-column p-4">
                        <div class="mb-4">
                            <input name="username" type="text" placeholder="Username" required class="form-control"
                                id="username" />
                            {% for error in form.username.errors %}
                                <p class="form-text error">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="mb-4">
                            <input name="email" type="text" placeholder="Email" required class="form-control"
                                id="email" />
                            {% for error in form.email.errors %}
                                <p class="form-text error">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="mb-4">
                            <input name="first_name" type="text" placeholder="First Name" required class="form-control"
                                id="first_name" />
                            {% for error in form.first_name.errors %}
                                <p class="form-text error">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="mb-4">
                            <input name="last_name" type="text" placeholder="Last Name" required class="form-control"
                                id="last_name" />
                            {% for error in form.last_name.errors %}
                                <p class="form-text error">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="mb-4">
                            <input name="password1" type="password" placeholder="Password" required class="form-control"
                                id="password" />
                            {% for error in form.password1.errors %}
                                <p class="form-text error">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="mb-4">
                            <input name="password2" type="password" placeholder="Confirm Password" required
                                class="form-control" id="password2" />
                            {% for error in form.password2.errors %}
                                <p class="form-text error">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="mb-4">
                            <button class="btn btn-primary rounded-pill w-100">Sign Up</button>
                        </div>
                        <div>
                            <p class="form-text">Already have an account? <a href="{% url 'core:sign-in' %}"
                                    class="link-primary">Click Here</a></p>
                        </div>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }} form-text" {% endif %}>{{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {% for error in form.non_field_errors %}
                            <p class="form-text error">{{ error }}</p>
                        {% endfor %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

core/templates/partials/navbar_auth.html
<nav class="py-3 mb-3 shadow-sm">
    <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
        <div>
            <a href="{% url 'core:homepage' %}"
                class="d-flex align-items-center col-lg-4 mb-2 mb-lg-0 link-dark text-decoration-none navbar-brand">
                Flash Forum
            </a>
        </div>

        <div class="d-flex align-items-center">
            <form class="w-100 me-3">
            </form>
            <div class="flex-shrink-0 dropdown">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ request.user.profile_photo.url }}" alt="profile-image" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'core:sign-out' %}">Sign out</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>

core/templates/partials/navbar_unauth.html
<!--- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
    <div class="container-fluid">
        <a href="{% url 'core:homepage' %}" class="navbar-brand">Flash Forum</a>
        <div class="d-flex">
            <a href="{% url 'core:sign-in' %}" class="rounded-pill btn btn-outline-primary">Sign In</a>
            <div class="p-2"></div>
            <a href="{% url 'core:sign-up' %}" class="rounded-pill btn btn-primary">Sign Up</a>
        </div>
    </div>
</nav>